build:
  system_packages:
    - "libssl-dev"
  python_packages:
    - "torchaudio==2.2.1"
    - "soundfile==0.12.1"
    - "transformers==4.41.1"
    - "git+https://github.com/suno-ai/bark.git@refs/pull/391/head"
